import esbuild from "esbuild";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import builtins from "builtin-modules";

const prod = process.argv.includes("production");
const banner =
  "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD if you want to view the source, please visit the github repository of this plugin */";
const repoRoot = path.dirname(fileURLToPath(import.meta.url));
const buildOptions = {
  absWorkingDir: repoRoot,
  banner: {
    js: banner
  },
  entryPoints: [path.join(repoRoot, "src", "main.ts")],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/state",
    "@codemirror/view",
    ...builtins
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  minify: prod,
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: path.join(repoRoot, "main.js")
};

if (prod) {
  await esbuild.build(buildOptions);
} else {
  const context = await esbuild.context(buildOptions);
  await context.watch();
}
